name: build
on: [push]
jobs:
    build_images:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php_version: ['8.0', '7.4', '7.3', '7.3-composer-1', '7.2', '5.6']
        steps:
            - uses: actions/checkout@v2
            - run: test/run_tests.sh ${{ matrix.php_version }}

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push PHP to Docker Hub
              uses: docker/build-push-action@v2
              with:
                  context: ./php/${{ matrix.php_version }}
                  # Note: tags has to be all lower-case
                  tags: |
                      jmleroux/php:${{ matrix.php_version }}
                  # build on feature branches, push only on main branch
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Build and push FPM to Docker Hub
              uses: docker/build-push-action@v2
              with:
                  context: ./fpm/${{ matrix.php_version }}
                  # Note: tags has to be all lower-case
                  tags: |
                      jmleroux/fpm:${{ matrix.php_version }}
                  # build on feature branches, push only on main branch
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
